export { default as Navbar } from "./navbar/Navbar"
export { default as Section1 } from "./pages/section1/Section1"
export { default as Section2 } from "./pages/section2/Section2"
export { default as Section3 } from "./pages/section3/Section3"
export { default as Section4 } from "./pages/Section4/Section4"
export { default as Section5 } from "./pages/section5/Section5"
export { default as Section6 } from "./pages/section6/Section6"